### ISSUE TITLE
module 'pygasflow' has no attribute 'atd'

### ISSUE THREAD

**Issue by DavidChartrand** [Davide-sd/pygasflow#9] opened 2024-11-05 16:12 UTC
I'm trying to calculate the compressible turbulent boundary layer but I have this error: 

```
bdl_comp_turb=pgf.atd.avf.thickness_fp.delta_tur_c(x_lin, Re_inf, T_r/T_inf, omega=1)
                  ^^^^^^^
AttributeError: module 'pygasflow' has no attribute 'atd'
```

If I try to import directly the atd or avf module I still get an error.

**Comment by Davide-sd** [comment] 2024-11-05 20:46
Thanks for pointing this out: I verified it.

At the moment, the only solution appears to be importing the functions like this:

```py
from pygasflow.atd.avf.thickness_fp import delta_tur_c
```

I'll look into it in the next few days. I've quickly inspected the file `setup.py` and it appears to be in order. Do you know if this is a regression? Did it work in previous versions?

**Comment by Davide-sd** [comment] 2024-11-06 14:35
I released a new version: hopefully the problem is fixed. I'm going to close this issue, but if you find that the problem is still there, reopen it and let me know.

The new version is already available on PyPI, it should be available on conda in a couple of days...

**Closed as completed by Davide-sd** 2024-11-06 14:35 UTC
